# Generated by Django 3.2.3 on 2021-05-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('age', models.IntegerField()),
                ('state_name', models.CharField(max_length=100)),
                ('state_id', models.IntegerField()),
                ('district_name', models.CharField(max_length=100)),
                ('district_id', models.IntegerField()),
            ],
        ),
    ]
