# Generated by Django 3.2.3 on 2021-05-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_email_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='District_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
            ],
        ),
    ]
