# Generated by Django 3.2.3 on 2021-05-26 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_district_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='District_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hos_id', models.IntegerField(unique=True)),
                ('hos_name', models.CharField(max_length=300)),
                ('hos_address', models.CharField(max_length=500)),
                ('hos_district', models.CharField(max_length=100)),
                ('hos_state', models.CharField(max_length=100)),
                ('min_age', models.IntegerField()),
                ('date', models.DateField()),
                ('dose1', models.IntegerField()),
                ('dose2', models.IntegerField()),
                ('avail', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.district_id')),
            ],
        ),
    ]
