# Generated by Django 3.2.3 on 2021-05-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_district_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='district_data',
            name='block',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='district_data',
            name='pin',
            field=models.IntegerField(null=True),
        ),
    ]
